version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    # THIS BIT!!!1!
    user: ${CURRENT_UID}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
