version: '3.7'
services:
  dev:
    image: node:12.16.1-alpine3.11
    volumes:
        - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dojo_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: