version: '3.7'
services:
  dev:
    image: node:12.16.1-alpine3.11
    volumes:
        - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start:dev
    ports:
      - 5200:5200

volumes:
  pgdata: